port: :10000
default_db:
  host: localhost
  port: 3306
  username: root
  password:
  database: paper_work
default_redis:
  host: localhost
  port: 6379
  db: 0
rule_server:
  url: http://localhost:10001
data_server:
  url: http://localhost:10002
